### PR TITLE
Add support for parsing LF delimited data. #29

### PR DESCRIPTION
**Pull request by stickybun**

### CODE REVIEW

**Comment by Yortw** [comment]
Thanks for the PR. They're always appreciated.

Can you tell me what device/service is sending data with only LF? I haven't seen that before. A quick check of the RFC seems to indicate the CRLF is the correct terminator and LF on it's own is not. If the device isn't updateable, then I guess I should merge this to ensure compatbility with non-compliant devices, but if it's possible to update whatever is sending these packets that would seem like a better idea.

From RFC 2616
"HTTP/1.1 defines the sequence CR LF as the end-of-line marker for all
   protocol elements except the entity-body (see appendix 19.3 for
   tolerant applications). The end-of-line marker within an entity-body
   is defined by its associated media type, as described in section 3.7.

       CRLF           = CR LF
"

https://tools.ietf.org/html/rfc2616

**Comment by stickybun** [comment]
Interesting!

I'll see if I can find out wherever I was whilst I was testing, and grab the responses.

**Comment by Yortw** [comment]
Thanks, I'll probably merge the change anyway but my development pc died today for the second time in a week and it will be Monday before I can start trying to reinstall it. Might be a while.

**Comment by stickybun** [comment]
Ok. I can't recreate now- wish I'd taken a snapshot of the response. 

Your call on merging. I can see how easily a project might send a LF - especially if they use file encoding to add carriage returns in their source code, like you are. 

Great project BTW. I've used many SSDP implementations in the past- and this has been the most reliable.

**Comment by Yortw** [comment]
The PR looks good and I'd rather the lib worked in practice than adhered strictly to spec, so I will merge this when I'm able. Thanks for checking for the source, and for the PR.

**Comment by Yortw** [comment]
Thanks also for the kind words about the library :)

**Comment by stickybun** [comment]
Great! No worries.

**Pull request merged**
