### PR TITLE
Added Additional Headers to Device Search Response

### PR DESCRIPTION
**Pull request by jay18001**

### CODE REVIEW

**Comment by Yortw** [comment]
Hi,

First of all, thanks heaps for submitting a PR for this, really nice to have someone take an interest and put in the effort to make changes them self. I sincerely appreciate the effort.

The code itself looks mostly fine and I'd love to merge it, but I have a couple of design/use case questions. There's also a couple of minor quality issues. Can we discuss?

Design/use case questions;

1. Should we perhaps add a property to the exsiting SsdpDeviceProperty class to indicate it should be included as a header, rather than adding an entirely different collection for these on the device? That might be simpler? This would also save the consumer duplicating values they want as a property of the device but also easily accessibly from the headers. One possible issue is caching. The device description document can be marked as cachable for custom periods, where as the device headers are sent on every search response so they could get out of sync during a cached period.

2. SSDP devices can be nested in a heirachy. The solution as provided seems to only provide the new headers for the immediate device a response is sent for. There's nothing that indicates whether this is deliberate, or just hasn't been thought about and the XML comment for the property doesn't tell the consumer what to expect. Should we include properties from the ancestorss? If a property exists on an ancestor and descendant with the same name, should the descendants values override the value from the ancestor, or should it be a header with multiple values?

3. Given the device already has custom properties, what is the need to have them included in the search header? I realise that an additional HTTP call is required to get the device properties if they're not included in the search response, but since only some devices are going to have the custom headers I would expect a fairly narrow search by type or id, so there wouldn't be too many additional queries to make?

4. The custom headers don't seem to be exposed on the locator end - the publisher has been updated to send them but it doesn't look like the search/locator engine as it exists exposes them? I feel if we're going to support publishing them, we should support retreiving them as well.

5. Assuming we keep the new collection instead of changing to the custom properties one, is the SsdpDevice class the right place for this? I realise on the publishing end there isn't really a better place for this in the current design, but it feels a bit wrong. Particularly on the retrieving end, where the headers probably should be exposed on the DiscoveredSsdpDevice class instead, as that's more about the search response than the device itself. 

Quality issues

1. The Xml documentation comment for the new property seems to be a copy and paste from the custom properties one. It doesn't really indicate what the new values are for, nor does it explain how nested device values are handled (or not).

2. No tests. Not demanding 100% coverage or anything, but I'd really like to see a test that confirms the custom headers are sent, and another to confirm the locator can retreive them properly too. Mostly this is to prevent stuff being possibly broken by future refactorings, and to give devs making changes confidence they haven't broken the existing system.

3. Although it probably doesn't make a signficiant difference most of the time, I'd prefer to use a StringBuilder to create the string for the additional header rather than potentially many string concatenations.

4. We may need to add some validation around the header property names. I'm not sure what the rules are for HTTP headers (will need to re-read the HTTP protocol spec to refresh my memory), but I suspect white space and/or : characters at least may not be allowed. At the moment it looks like it would be possible to include a property which would create an incorrect header and is likely to cause errors on clients. We could either validate them at time of add, or perhaps try to convert them to valid header names at time of publish, but I think validation is the way to go. That might be a strike against using the existing collection property though, since they don't have the same limitations.

**Comment by jay18001** [comment]
1. Adding like a bool or something on to dictate if it should be no a header or not would work, but I used a separate collection to make it easier to implement. The cashing problem would happen if the headers are added or but it should be up to user should handle that as necessary.

2. It's really should be handled on a case by case bases. It really should be a enum or something so the user can decide how they want child devices headers to work.

3. To answer this question it might help to give some background on what I doing, I'm having an iOS device search the network for SSDP devices, I added a header to show the machine name so I can show a friendlier name for the user. It just so I don't have to add a bunch of HTTP calls.

4. The problem is we don't know on the client side which are the custom headers besides checking against the standard. So the best way would have to bring down all the headers to the delegate call backs.

5. See above.


1. Sorry about that, I'm used to not documenting code. I'll fix it.

2. I'll look into adding some

3.Thats an easy change.

4. I believe the name must be ASCII with no spaces. However the value can be unicode without newlines. We can check the vales when the property is added to the collection.

**Comment by Yortw** [comment]
I'm happy to just use the properties from the immediate device, as the code currently does, so long as we document that in the remarks section of the xml comments for the property so that consumers know that's how it works. We can always add a property to the publisher later if we decide to enable support for 'hierachical' custom headers.

Also happy to have all the headers, not just custom ones, accessible from the device locator. Are you using an iOS API to do the search? I assume you must be because RSSDP doesn't currently expose the headers?

I can't decide if we should use the existing properties or keep your new collection. The machine name doesn't really seem like a property of the device itself, so that makes the new collection seem like a better idea, but it's not 100% clear to me. Validation seems difficult in either case. We need a new collection type that does the validation if we keep the new collection property. If we use the existing properties collection then we need to validate on add if the new property is set, but also when the property changes, which seems slightly harder. I think perhaps the new collection is the way to go - it seems cleaner on the receiving end - don't really want to mix the usual/standard HTTP headers with the actual device properties from the description document.

Sorry to be fussy about the comments and tests, but as it's a publicly published library I'd like to keep it as usuable and pleasant to consume as possible.

Thanks.

**Comment by Yortw** [comment]
Let me know if you need help with any of the changes.

**Comment by jay18001** [comment]
On iOS I just using the an Objective-C wrapper around the C apis. (I tend to stay away from the cross platform stuff)

[CocoaAsyncSocket](https://github.com/robbiehanson/CocoaAsyncSocket)

Then it spits out this header
```
HTTP/1.1 200 OK
EXT:
DATE: Sat, 02 Jan 2016 19:52:25 GMT
CACHE-CONTROL: public, max-age=300
ST:urn:my-namespace:device:MyCustomDevice:1
SERVER: Win32NT/6.2.9200.0  UPnP/1.0 RSSDP/1.0
USN:uuid:B7FCCB48-1229-458C-9A98-183E6D261B2C::urn:my- namespace:device:MyCustomDevice:1
LOCATION:http://mydevice/descriptiondocument.xml
machineName:Windows-pc-one
```

About the test cases and comments, I added them in the last commit and also exposed the headers on the device locator, at least on the response delegate call back. I think it really should be on all of them.

**Pull request merged**
