### PR TITLE
Feature/ipv6 support

### PR DESCRIPTION
**Pull request by qine**
Hi,

I have not added support for the following projects: UWP10, WindowsPhoneSL and WinRT
I have the devices that support UPnP via ipv6; search and publishing works correctly

### CODE REVIEW

**Comment by Yortw** [comment]
Wow, thanks for this. It's hugely appreciated.
Unfortunately given the size of the PR and my currnet commitments it will take me sometime to review. Additionally it is important to me to keep feature parity across the platforms (especially UWP), so I may need to do extra work to implement your changes on those platforms before release.

Thanks again. Watch this space.

**Comment by Yortw** [comment]
Hi,

I see that this always targets the link-local, site-local, and global ipv6 multicast address ranges.
Is this neccesary, and is it a good idea?
In terms of neccesary, do you know if packets sent to the global address will be received by notes on the link & site local addresses as well as being routed across the internet (I would assume so, but I am not an expert on networking at this level)? If so, then targeting only the highest scope would be neccesary and we could send fewer messages?

In terms of is it a good idea, I have an application where I specifically would not want the packets routed over the internet, and more important not over VPN/WAN connections. I would specifically want the packets limited to the local network. Possibly rather than assume everybody wants everything to go everywhere, we should either assume a more restictive scope, or provide a property/flag/option to set the scope(s)?

**Comment by qine** [comment]
Oh, when I started to think about your words, I have to see this description: We should not use global addresses.

I think the opportunity to indicate to which addresses will participate in the multicast delivery (link-local, site-local, org-local) is the best idea.

annex

**Comment by qine** [comment]
Let me add some opportunity to specify the multicast addresses scopes

**Pull request merged**
