### PR TITLE
Feature .NET Core Support

### PR DESCRIPTION
**Pull request by stickybun**
**For review**

I have created a new NetCore project, which targets .NET Standard 1.3 - and can be used in .NET Core applications.

It appears you try and avoid compiler directives, so have tried to keep these to a minimum in the shared code.

Because the PCL shared library uses Microsoft.Bcl.Async/Build and Microsoft.Net.Http libraries (not supported in Core), I've had to link the sources directly into the project, under the Portable folder.

Let me know what you think. I haven't thoroughly tested this yet in real environments. 

P.S. couldn't work out how to create pull request against a new branch. I can re-do this if you create one.

### CODE REVIEW

**Comment by Yortw** [comment]
Hi,

Thanks so much for your effort on this! I really appreciate the PR.
I'm at work so have only glanced at the code, it will be a little while before I can review more thoroughly, but it looks good to me so far. Probably it's exactly what I would have done. Just a couple of things;

1. I think the nuspec might need a change, but am not sure. The NetCore version you've created doesn't use the HTTP/bcl libraries, but I *think* the nuspec as it stands will still include them at install time. We possibly need to add a target framework to the dependency group that includes those libraries, or add an exclusion for netcore etc. I'm not sure what's possible, will have to confirm it's an issue and check the nuget docs.

2. Is NetStandard 1.3 the minimum net standard version we can target (or is there another reason to use that instead of an earlier versioon)? Happy if so, but would like to maximise targets where possible.

3. I'm not terribly familiar with netcore. I see the net standard library dependency in the nuspec is v1.6 - I assume that is the correct version for 'netstandard 1.2' and not a typo?

4. I'll create a branch for you, would be nice to have this in a branch while we iron out any little details like the above.

**Comment by Yortw** [comment]
Created the branch Feature-NetCoreSupport in the main repo for you.

**Comment by Yortw** [comment]
Ignore the failing build/test, I *think* that test is flaky and needs fixing. Probably works fine run locally. Will check when I have time.

**Comment by stickybun** [comment]
Thanks for looking at this!

I have no immediate need for this feature - just collecting requirements for a future project - so I'm happy to take the time to get it right.

1. I wasn't sure either about this, but *weakly* according to [the nuspec schema](https://docs.nuget.org/ndocs/schema/nuspec), it's referred to as a fallback group. It appears to be working this way in test. But I'm not convinced.
    > targetFramework Optional. The target framework of the group. If not set, the group acts as a fallback group, which behaves exactly as before version 2.5.

2. Pretty sure 1.3 is the lowest you can go with sockets. I quite like this cheeky guide by david fowler [Analogy of the NetStandard API as interfaces](https://github.com/davidfowl/NetStandard/blob/master/platforms.cs) 

3. Yeah, this is probably incorrect - it's a bit of a sledgehammer approach - rather than adding the specific dependencies - it basically just represents **all** of the packages in the [List of .NET CoreFx APIs](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#list-of-net-corefx-apis-and-their-associated-net-platform-standard-version) - I shall change this and the nuspec to refer to the exact dependencies.

4. Thanks for creating the branch - I've changed the PR to use that.

**Comment by stickybun** [comment]
With regards to 1. this tool was mentioned in a couple of posts, and seems to imply that multiple groups/targetFramework sections make the package more reliable? [ReferenceGenerator tool](https://github.com/onovotny/ReferenceGenerator#packages-containing-netstandard-and-existing-libraries)
  > If you have a package that contains a netstandard group and your users use packages.config, you may want to add blank dependency groups.

**Comment by stickybun** [comment]
OK, I've updated the PR

1. It appears the fallback group behaves differently than the target DLL choice - so that for example, UWP or .NET 4.6 will pick the correct DLL's (PCL + Native) - but choose the .NET standard dependency group! So adding the specific targets to match the DLL's makes them behave the same. I suppose this means that UWP + 4.6 could probably use the .NET Standard DLL now - but I'm not sure of the implications.

2. N/A

3. I've updated the dependencies to be the actual requirements for this project.

**Comment by Yortw** [comment]
Thanks for the updates. I was hoping to look at this last night but didn't get a chance, my new plan is to try and find some time on the weekend.

I feared there was some problem with the Nuget dependency groups, but couldn't quite remember why. I think you're explanation is exactly what I'd encountered in the past, and the reason to target the groups explicitly.

> I suppose this means that UWP + 4.6 could probably use the .NET Standard DLL now - but I'm not sure of the implications.

This *should* actually be a good thing. The Microsoft HTTP Libraries and their dependencies are required for the older platforms, but not the new ones. Unfortunately since the current design has a single PCL that is used across all the targets, all of them need the dependencies. The 'build' dependencies are quite nasty too, as they end up spreading to every project that references RSSDP. 

Since you've shared/compiled the code from the PCL into the Net Standard library, it doesn't need those dependencies, so any platform supporting/using that reference can drop the dependencies too. This is a bonus.

It's just a question of whether there's any unknown issues resulting from doing that. There shouldn't be.

**Comment by Yortw** [comment]
This is now published via nuget. Thanks for all your work, I tested the changes and did some unrelated clean up work, but all of your stuff seemed perfect just as it was.
Thanks heaps for the PR.

**Comment by stickybun** [comment]
Excellent! That's good news!

**Pull request merged**
