### PR TITLE
Enable optional locking around logging write

### PR DESCRIPTION
**Pull request by BruceMellows**
Enable optional locking around logging write which is opt-in so that
clients that do not need this facility will not need to change and would
not have any change in behaviour

### CODE REVIEW

**Comment by BruceMellows** [comment]
The application still crashed even the the lock was taken, so this is NOT a solution. This should be closed and rejected. Thanks.

**Comment by Yortw** [comment]
Hi Bruce,

Pretty disappointing that didn't solve the problem and I'm not sure what to suggest at this point, but thanks for making the PR anyway. Let me know if I can help. If you can send me a small project that reproduces the issue reliably I may be able to find time to look myself (eventually ;) ).

**Comment by BruceMellows** [comment]
This was embarrassingly easy to fix in the end, just remove the "output tracing to stdout" section in the .exe.config (the app is not a console app). I.E. delete the following ...

> <system.diagnostics>
>   <trace autoflush="true">
>     <listeners>
>       <add name="consoleListener" type="System.Diagnostics.ConsoleTraceListener" />
>     </listeners>
>   </trace>
> </system.diagnostics>

**Comment by BruceMellows** [comment]
Trying again (with preview)

`<system.diagnostics><trace autoflush="true"><listeners><add name="consoleListener"  type="System.Diagnostics.ConsoleTraceListener" /></listeners></trace></system.diagnostics>
`

**Comment by Yortw** [comment]
It's only easy when you already know how :)
Glad you solved it!

**Pull request closed without merging**
